<!DOCTYPE html>
<html>
<head>
    <title>Select2 Dropdown</title>
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Select2 CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <link href="../plugins/select2/select2.min.css" rel="stylesheet" type="text/css" />
    <!-- Select2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
</head>
<body>
    <!-- Select element -->
    <select class="js-example-basic-single" name="state">
        <option value="AL">Alabama</option>
        <!-- Options will be dynamically generated by PHP -->
    </select>

    <!-- JavaScript code -->
    <script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2({
            placeholder: 'Select a user ID',
            allowClear: true
        });
    });
    </script>
</body>
</html>
